BTM/Pages/Kunden/Details.cshtml.cs
using BTM.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Syncfusion.DocIO.DLS;
using Syncfusion.DocIO;
using DocumentFormat.OpenXml.Packaging;
using DocumentFormat.OpenXml.Wordprocessing;
using DocumentFormat.OpenXml;
using Microsoft.AspNetCore.Mvc.Rendering;
using BTM.Data.DBAccess;

namespace BTM.Pages.Kunden
{
    public class DetailsModel : PageModel
    {
        [BindProperty]
        public Kunde CurrentCostumer { get; set; }
        [BindProperty]
        public Devices Devices { get; set; }
        [BindProperty]
        public Telefon Telefon { get; set; }
        [BindProperty]
        public Counters Counters { get; set; }
        public List<Tuple<Devices, Counters>> LastCounter { get; set; }
        [BindProperty]
        public string ColorMessage { get; set; }
        [BindProperty]
        public string BlackWhiteMessage { get; set; }
        [BindProperty]
        public string GesamtMessage { get; set; }
        [BindProperty]
        public bool Color { get; set; }
        [BindProperty]
        public bool Black { get; set; }
        [BindProperty]
        public bool Gesamt { get; set; }
        [BindProperty]
        public Devices CurrentDevice { get; set; }
        [BindProperty]
        public string NewName { get; set; }
        

        private readonly IDevices _dev;
        private readonly ICostumer _db;
        public DetailsModel(ICostumer db, IDevices dev)
        {
            _db = db;
            _dev = dev;
        }
        public void OnGet(int id)
        {
            Counters = new Counters();
            CurrentCostumer = _db.GetCostumer(id);
            NewName = CurrentCostumer.Name;
            LastCounter = _db.GetAllLastCountersOfKunde(id);
            var test = CurrentDevice;
            
        }
        public IActionResult OnPost(int ID)
        {
            _db.UpdateCostumer(CurrentCostumer);
            return this.RedirectToPage();
        }
        public IActionResult OnPostAddPhone(int ID)
        {
            var phone = Telefon;
            phone.KundenID = ID;
            _db.AddTelephone(phone);
            return this.RedirectToPage();
        }
        public IActionResult OnPostAddDevice(int ID)
        {
            var dev = this.Devices;
            dev.KundenID = ID;            
            _db.AddDevice(dev);            
            return RedirectToPage();
        }
        public IActionResult OnPostAddCounter(int ID)
        {
            Color = true;
            Black = true;
            Gesamt = true;
            var nextQuartal = false;
            var counter = this.Counters;
            counter.DateTime = DateTime.Now;
            var lastCounter = _db.GetLastCounterOfDevice(counter.DeviceID);

            nextQuartal = lastCounter.QuartalYear < counter.QuartalYear ||
               (lastCounter.QuartalYear == counter.QuartalYear && lastCounter.Quartal < counter.Quartal);

            

            if (lastCounter.ColorCounter > counter.ColorCounter)
            {
               ViewData["Color"] = "Error";
                Color= false;
            }
            if (lastCounter.CounterSum > counter.CounterSum)
            {
                Gesamt = false;
            }
            if (lastCounter.BlackWhiteCounter > counter.BlackWhiteCounter)
            {
                Black = false;
            }            
            if (Black && Color && nextQuartal)
            {
                _db.AddCounters(counter);
                CurrentCostumer = _db.GetCostumer(CurrentCostumer.ID);
                CurrentCostumer.InvoiceIsCreated = false;
                _db.UpdateCostumer(CurrentCostumer);
            }
            return RedirectToPage();

        }
        public IActionResult OnPostRemoveCounter(int CounterID)
        {
            _db.RemoveCounter(CounterID);
            return RedirectToPage();
        }
        public IActionResult OnPostCalculateCounters(int ID)
        {
            return RedirectToPage("./Evaluation", new { ID });
        }
        public IActionResult OnPostEditDevice(int DeviceID)
        {
            return RedirectToPage("./EditDevice", new { DeviceID });
        }
        public IActionResult OnPostBack()
        {
            return RedirectToPage("./Index");
        }
        public IActionResult OnPostDeleteDevice(int DeviceID)
        {
            _db.HideDevice(DeviceID);
            return RedirectToPage();
        }
       
        public IActionResult OnPostDeletePhone(int phoneID)
        {
            _db.RemovePhone(phoneID);
            return RedirectToPage();
        }
        public IActionResult OnPostUpdateName()
        {
            var NewCostumer = _db.GetCostumer(CurrentCostumer.ID);
            if (!string.IsNullOrWhiteSpace(NewName))
            {
                NewCostumer.Name = NewName;
                _db.UpdateCostumer(NewCostumer);
            }                
            return RedirectToPage();
        }

    }
}

BTM/Pages/Kunden/EditDevice.cshtml.cs
using BTM.Data;
using BTM.Data.DBAccess;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BTM.Pages.Kunden
{
    public class EditDeviceModel : PageModel
    {
        [BindProperty]
        public Devices CurrentDevice { get; set; }

        private readonly IDevices _dev;
        public EditDeviceModel(IDevices dev)
        {
        _dev= dev;
        }

        public void OnGet(int DeviceID)
        {
            CurrentDevice=_dev.GetDevicesById(DeviceID);
        }
        public IActionResult OnPostSave() 
        {
            //Save
            _dev.UpdateDevice(CurrentDevice);
            return RedirectToPage("./Details", new {ID=CurrentDevice.KundenID});
        }
        public IActionResult OnPostBack()
        {
            return RedirectToPage("./Details", new { ID = CurrentDevice.KundenID });
        }
    }
}

BTM/Pages/Kunden/Evaluation.cshtml.cs
using BTM.Data;
using BTM.Data.DBAccess;
using BTM.Data.Enums;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BTM.Pages.Kunden
{
    public class EvaluationModel : PageModel
    {
        private readonly ICostumer _costumer;
        private readonly IDevices _devices;
        public EvaluationModel(ICostumer costumer,IDevices devices)
        {
            _costumer = costumer;
            _devices = devices;
        }
        [BindProperty]
        public List<Devices> Devices { get; set; }
        [BindProperty]
        public Kunde Costumer { get; set; }
        public void OnGet(int Id)
        {
            Costumer = _costumer.GetCostumer(Id);
            Devices = _devices.GetDevicesByCustomerID(Id,null);
        }
        public IActionResult OnPostBack(int ID)
        {
            return RedirectToPage("./Details", new {ID});
        }
    }
}

BTM/Pages/Kunden/Index.cshtml.cs
using BTM.Data;
using BTM.Data.DBAccess;
using BTM.Data.Enums;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BTM.Pages.Kunden
{
    public class IndexModel : PageModel
    {
        private ICostumer _costumer { get; set; }
        private IDevices _devices { get; set; }

        private readonly ILogger<IndexModel> _logger;
        public IndexModel(ILogger<IndexModel> logger, ICostumer costumer,IDevices devices)
        {
            _logger = logger;
            _costumer = costumer;
            _devices = devices;
            SelectedQuartal=_devices.GetCurrentQuartal();
            SelectedYear=DateTime.Now.Year;
        }
        [BindProperty]
        public List<Kunde> AllCostumers { get; set; }
        [BindProperty(SupportsGet = true)]
        public Quartal SelectedQuartal { get; set; }
        [BindProperty(SupportsGet = true)]
        public int SelectedYear { get; set; }
        [BindProperty]
        public Kunde Costumer { get; set; }
        [BindProperty(SupportsGet = true)]
        public string Search { get; set; }
        public void OnGet()
        {
            var filter = new Filter() { SearchQuartal= SelectedQuartal,SearchYear=SelectedYear };
            AllCostumers = _costumer.GetAllCostumers(Search,filter);
            if (AllCostumers == null)
                AllCostumers = new List<Kunde>();

            Costumer = new Kunde { Email = string.Empty, Standort = string.Empty };
        }
        public IActionResult OnPostCreate()
        {
            var kunde = _costumer.AddNewCostumer(this.Costumer);
            if (kunde != null)
            {
                Costumer=kunde;
            }
            return RedirectToPage("./Details",new {Id=kunde.ID });
        }
        public IActionResult OnPostDetail(int ID)
        {
            return RedirectToPage($"./Details",new {Id=ID });
        }
        public IActionResult OnPostAddFilter()
        {
            return RedirectToPage();
        }

    }
}

BTM/Pages/Kunden/EditDevice.cshtml
@page "{DeviceID:int?}"
@using BTM.Data.Enums;
@model BTM.Pages.Kunden.EditDeviceModel
@{
    ViewData["Title"] = "Gerät editieren";
}

<html>
<h3>Gerät ändern</h3>
<form method="post">
    <input type="hidden" asp-for="CurrentDevice.KundenID" />
    <input type="hidden" asp-for="CurrentDevice.ID" />

    <div class="form-control">

        <div class="input-group">
            <div class="input-group mb-3">
                <span class="input-group-text">Name</span>
                <input type="Text" class="form-control" placeholder="Gerätename" asp-for="CurrentDevice.DeviceName" required />
            </div>
            <div class="input-group mb-3">
                <span class="input-group-text">Nummer</span>
                <input type="text" class="form-control" placeholder="Gerätenummer" asp-for="CurrentDevice.DeviceNumber" required />
            </div>
            <div class="input-group mb-3">
                <span class="input-group-text">Beschreibung</span>
                <textarea type="text" class="form-control" placeholder="Druckerbeschreibung" asp-for="CurrentDevice.Description" required></textarea>
            </div>
            <div class="input-group mb-3">
                <span class="input-group-text">Standort</span>
                <input type="text" class="form-control" placeholder="Standort" asp-for="CurrentDevice.Standort" required />
            </div>
            <div class="input-group mb-3">
                <span class="input-group-text">Frei Kopien Farbe</span>
                <input type="number" class="form-control" placeholder="Farbe" asp-for="CurrentDevice.FreePrintsColor" value="0" />
            </div>
            <div class="input-group mb-3">
                <span class="input-group-text">Frei Kopien Schwarz/Weiß</span>
                <input type="number" class="form-control" placeholder="Farbe" asp-for="CurrentDevice.FreePrintsBlackWhite" value="0" />
            </div>
            <div class="input-group mb-3">
                <span class="input-group-text">Vertrag</span>
                <select class="custom-select" asp-items="Html.GetEnumSelectList<Verträge>()" asp-for="CurrentDevice.VertragsID" required>
                </select>

            </div>
        </div>
        <div>
            <button type="submit" asp-page-handler="Save">Speichern</button>
            <button type="button" data-bs-toggle="modal" data-bs-target="#Back" style="float:right">Abrechen und Zurück</button>
            <div class="modal fade" id="Back" tabindex="-1" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h1 class="modal-title fs-5" id="Back">Vorgang Abbrechen?</h1>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            Wollen sie wirklich abbrechen?
                            Alle vorgenommenen änderungen werden nicht gespeichert.
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Nein nicht abbrechen</button>
                            <button type="button" class="btn btn-danger">
                                <a class="text-black" asp-page="./Details" asp-route-Id="@Model.CurrentDevice.KundenID">Ja abbrechen und zurück</a>
                            </button>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</form>
</html>

BTM/Pages/Kunden/Evaluation.cshtml
@page "{Id:int?}"
@using System.Reflection
@using BTM.Data.Enums
@model BTM.Pages.Kunden.EvaluationModel
@{
}
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous" />
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css">
<!-- Bootstrap Font Icon CSS -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
<html>
<header>
</header>
<body>
    <h3 style="text-align:center">Abbrechnung für Kunde: @Model.Costumer.Name</h3>
    <form method="post">
        <div><button class="btn btn-secondary" asp-page-handler="Back"><i class="bi bi-arrow-return-left">  Zurück</i></button></div>

    </form>

    <br />
    <br />
    <div>
        <table class="table">
            <thead>
                <tr>
                    <td>Gerätenamen</td>
                    <td>Vertrag</td>
                    <td class="table-active"></td>
                    <td class="table-active">letztes Quartal</td>
                    <td class="table-active"></td>
                    <td></td>
                    <td class="table-active"></td>
                    <td class="table-active">aktuelles Quartal</td>
                    <td class="table-active"></td>

                    <td>Freikopien</td>
                    <td class="table-active table-success"></td>
                    <td class="table-active table-success">Abzurechnende Kopien</td>
                </tr>
                <tr>
                    <td></td>
                    <td></td>
                    <td class="table-active">Quartal</td>
                    <td class="table-active">Farbe</td>
                    <td class="table-active">Schwarz/Weiß</td>
                    <td></td>
                    <td class="table-active">Quartal</td>
                    <td class="table-active">Farbe</td>
                    <td class="table-active">Schwarz/Weiß</td>
                    <td>Farbe/SchwarzWeiß</td>
                    <td class="table-active table-success">Farbe</td>
                    <td class="table-active table-success">Schwarz/Weiß</td>

                </tr>
            </thead>
            <tbody>
                @foreach (var device in Model.Devices)
                {
                    @if (device.Counters.Count >= 2)
                    {


                        <tr>
                            <td>@device.DeviceName</td>
                            <td>
                                @{
                                    @foreach (var value in @EnumHelper<Verträge>.GetValues(device.VertragsID))
                                    {
                                        if (value == device.VertragsID)
                                        {
                                            var description = EnumHelper<Verträge>.GetDisplayValue(value);
                                            @Html.DisplayFor(e => description )
                                        }
                                    }
                                }
                            </td>
                            <td class="table-active" style="text-align:center">@device.Counters.OrderByDescending(x=>x.DateTime).ToList()[1].QuartalYear @device.Counters.OrderByDescending(x=>x.DateTime).ToList()[1].Quartal</td>
                            <td class="table-active" style="text-align:center">@device.Counters.OrderByDescending(x=>x.DateTime).ToList()[1].ColorCounter</td>
                            <td class="table-active" style="text-align:center">@device.Counters.OrderByDescending(x=>x.DateTime).ToList()[1].BlackWhiteCounter</td>
                            <td></td>
                            <td class="table-active" style="text-align:center">@device.Counters.OrderByDescending(x=>x.DateTime).ToList()[0].QuartalYear @device.Counters.OrderByDescending(x=>x.DateTime).ToList()[0].Quartal</td>
                            <td class="table-active" style="text-align:center">@device.Counters.OrderByDescending(x=>x.DateTime).ToList()[0].ColorCounter</td>
                            <td class="table-active" style="text-align:center">@device.Counters.OrderByDescending(x=>x.DateTime).ToList()[0].BlackWhiteCounter</td>
                            <td style="text-align:center">@device.FreePrintsColor/@device.FreePrintsBlackWhite</td>
                            <td class="table-success" style="text-align:center">@device.ColEval</td>
                            <td class="table-success" style="text-align:center">@device.BlackWhiteEval</td>

                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>
</body>
</html>

BTM/Pages/Kunden/Index.cshtml
@page
@using BTM.Data.Enums;
@model Pages.Kunden.IndexModel
@{
    ViewData["Title"] = "Übersicht";
}
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous" />
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css">
<!-- Bootstrap Font Icon CSS -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
<style>
    .right {
        float: right
    }

    .left {
        float: left
    }
</style>
<html>
<head>
</head>
<body>

    <div class="right">
        <form method="post">
            <div class="input-group mb-3">
                <input type="hidden" asp-for="Costumer.ID" />
                <input type="hidden" asp-for="Costumer.Email" />
                <input type="hidden" asp-for="Costumer.Standort" />

                <input type="text" class="form-control" placeholder="Neuer Kundenname" asp-for="Costumer.Name" required>
                <span class="text-danger" asp-validation-for="Costumer.Name"></span>
                <div class="invalid-feedback">
                    Name is required!
                </div>
                <button class="btn btn-outline-secondary" asp-page-handler="Create" type="submit">Erstellen</button>
            </div>
        </form>
    </div>
    <div class="left">
        <form method="get">
            <div class="input-group mb-3">
                <input type="hidden" asp-for="SelectedQuartal"/>
                <input type="hidden" asp-for="SelectedYear"/>
                <input type="text" class="form-control" placeholder="Suchen nach..." asp-for="Search" />
                <button class="btn btn-outline-secondary" asp-page-handler="Search" type="submit">Suchen</button>
            </div>
        </form>
    </div>


    <div class="">
        <table class="table">
            <form method="get">
                <input type="hidden" asp-for="Search"/>
            <thead>
                <tr>
                    <td>Rechnung erstellt?</td>
                    <td>
                        Kunden Name
                    </td>
                    <td>
                        Kunden Email
                    </td>
                    <td>
                        <div>
                         <select class="select" asp-items="Html.GetEnumSelectList<Quartal>()" asp-for="SelectedQuartal" onchange="this.form.submit();"></select>
                        <select class="select" asp-for="SelectedYear" onchange="this.form.submit();">
                            <option>2022</option>
                            <option>2023</option>
                            <option>2024</option>
                            <option>2025</option>
                            <option>2026</option>
                        </select>                     
                        </div>
                          
                        Aktueller Zählerstand vorhanden?
                    </td>
                    <td>
                        Standort
                    </td>

                    <td>Telefon</td>

                    <td></td>
                </tr>
            </thead>
            </form>
            <form method="post">
            <tbody>
                    @foreach (var item in Model.AllCostumers.OrderBy(x => x.Name))
                    {
                    <tr>
                        <td width="75"><div class="@(item.InvoiceIsCreated ? "green" : "red")">@(item.InvoiceIsCreated ? "Ja" : "Nein")</div></td>
                        <td>
                                @item.Name

                        </td>
                        <td>
                                @item.Email
                        </td>
                        <td>
                            <div class="@(item.IsUpToDate ? "green" : "red")">@(item.IsUpToDate ? "Ja" : "Nein")</div>
                        </td>

                        <td>
                                @item.Standort
                        </td>

                        <td>
                                @if (item.Telefons != null && item.Telefons.Count() > 0)
                                {
                                    @foreach (var phone in item.Telefons)
                                    {
                                    <div class="row">
                                            @phone.Name : @phone.TelefonNummer
                                    </div>
                                    }
                                }
                        </td>
                        <td>
                            <button type="submit" asp-page-handler="Detail" asp-route-ID="@item.ID" value="detail" class="btn btn-secondary">
                                <i class="bi bi-pencil-square"></i>
                            </button>
                        </td>
                    </tr>

                    }
            </tbody>
            </form>

        </table>
    </div>

</body>
</html>

<style>
    .green {
        background-color: rgba(0, 255, 0, 0.5);
        text-align: center;
        font-weight: bold;
    }

    .red {
        background-color: rgba(255, 0, 0, 0.5);
        text-align: center;
        font-weight: bold;
    }
</style>